#!/usr/bin/env bash
# Installs nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# changes the owner to current user to write
sudo chown -R "$USER":"$USER" /var/www/html/
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/

# configures output
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# updates config file to redirect
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=mMfMTPxLEZU permanent;" /etc/nginx/sites-available/default
sed -i "/server_name _;/ a\\\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default

# starts engine or restart
sudo service nginx restart
