#!/usr/bin/env bash
# Creates a script to install and configure HAProxy on lb-01 server
# Configures HAProxy to send traffic to web-01 and web-02 servers
# Distributes requests using a roundrobin algorithm
# makes sure HAProxy can be managed via an init script

# Installs and configures HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edits config file
server_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 176572-web-01 54.165.168.252:80 check
        server 176572-web-02 34.237.91.136:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enables haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Tests HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restarts Nginx service
sudo service haproxy restart
