#!/usr/bin/env bash
# Installs, configures, starts the load balancer
# Updates package lists
sudo apt-get update

# Installs HAProxy
sudo apt-get install haproxy -y

# Configures HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 18.204.6.193:80 check
    server web-02 54.84.40.70:80 check
EOT

# Tests HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Starts HAProxy
sudo systemctl start haproxy

# Enables HAProxy to start on boot
sudo systemctl enable haproxy
