#!/usr/bin/env bash
# configures new HAproxy as load balancer

# Installation of HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configures haproxy configuration file to distribute requests using roundrobin algorithm
echo '
frontend http_back
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 279848-web-01 18.204.6.193:80
        server 279848-web-02 54.84.40.70:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
